name: Swift

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        destination: [
          'platform=iOS Simulator,OS=10.3.1,name=iPhone 7',
          'platform=iOS Simulator,OS=11.4,name=iPhone 8',
          'platform=iOS Simulator,OS=12.4,name=iPhone X',
          'platform=iOS Simulator,OS=13.5,name=iPhone 11',
          'platform=tvOS Simulator,OS=10.2,name=Apple TV',
          'platform=tvOS Simulator,OS=11.4,name=Apple TV',
          'platform=tvOS Simulator,OS=12.4,name=Apple TV',
          'platform=tvOS Simulator,OS=13.3,name=Apple TV',
          'platform=macOS'
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
